---
 -  hosts: node2
    become: yes
    tasks:
      - name: Install nginx
        shell: "apt update && apt install nginx -y"
      - name: start & enable nginx
        shell: "systemctl enable nginx && systemctl start nginx"
      - name: Create a sample HTML file
        copy:
        dest: /var/www/html/index.html
        content: "<h1>Welcome to Nginx!</h1>"





